
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
        id: release_version
      - run: make release
        env:
          RELEASE_VERSION: ${{ steps.release_version.outputs.RELEASE_VERSION }}
      - name: Create Release
        id: create_release
        run: gh release create ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v1
        with:
          registry: registry.replicated.com
          username: ${{ secrets.REPLICATED_REGISTRY_SECRET }}
          password: ${{ secrets.REPLICATED_REGISTRY_SECRET }}
      - name: Push to Replicated
        id: release_replicated
        run: make release-replicated
        env:
          RELEASE_VERSION: ${{ steps.release_version.outputs.RELEASE_VERSION }}
